### ISSUE TITLE
configure on non-deploy task

### ISSUE THREAD

**Issue by chulkilee** [mattbrictson/airbrussh#1]
I'm using just Capfile and rake task files.

```ruby
# Capfile
require 'capistrano/setup'
require 'airbrussh/capistrano'

Dir[File.expand_path('./lib/tasks/**/*.rake', __dir__)].each { |f| import f }

set :stage, :production
set :log_level, :debug
````

```ruby
# example of rake task
namespace :ubuntu do
  task :update do
    on roles(:ubuntu) do
      execute 'sudo apt-get -qq update && sudo apt-get -qq -y upgrade'
    end
  end
```

It turns out that airbrussh is not loaded - I had to put following code at the end of `Capfile`

```ruby
SSHKit.config.output = Airbrussh::Formatter.new($stdout)
```

It is same on sshkit 1.7.1 and 1.6.1. I'm using capistrano 3.4.0

**Comment by mattbrictson** [comment]
Interesting! So you are using capistrano with a `Capfile` by itself, with no `deploy.rb` or stage files? I wasn't aware of that use case.

Could you add `--trace` to one of your cap executions so that I can see what rake tasks are being run?

E.g.

```
$ cap production deploy deploy:check --trace
** Invoke production (first_time)
** Execute production
** Invoke load:defaults (first_time)
** Execute load:defaults
```

Airbrussh installs itself during `load:defaults`, which should always be run by capistrano, but maybe not in your case...

**Comment by chulkilee** [comment]
Oh I found the problem..

- SSHKit format is set in [configure_backend](https://github.com/capistrano/capistrano/blob/v3.4.0/lib/capistrano/configuration.rb#L82)
- configure_backend is called for each stages ([ref](https://github.com/capistrano/capistrano/blob/v3.4.0/lib/capistrano/setup.rb#L18))

The problem is that in my setup there is no stages since stages are retrieved from file name, not value - [ref](https://github.com/capistrano/capistrano/blob/v3.4.0/lib/capistrano/dsl/stages.rb#L6).

So I ended up added following files for capistrano stage.

- config/deploy.rb
- config/deploy/all.rb

I'm closing it for now since this issue comes from specific (probably wrong) capistrano setup.

Thanks for the quick response!
