### ISSUE TITLE
how do I show the actual commands being executed as well as the airbrush indented output?

### ISSUE THREAD

**Issue by mikeni** [mattbrictson/airbrussh#11]
how do I show the actual commands being executed as well as the airbrush indented output?

**Comment by robd** [comment]
Hey Mike
Does the `config.command_output` help? - https://github.com/mattbrictson/airbrussh#usage
Could you give an example of what output you see and what you would like?

**Comment by mattbrictson** [comment]
Closing for now due to lack of information.
