### ISSUE TITLE
When deploying the same version, airbrussh log spits out an error.

### ISSUE THREAD

**Issue by jaipandya** [mattbrictson/airbrussh#12]
When last revision SHA of last deployment and current deployment happens to be same. I received the following error message:

`fatal: ambiguous argument '8849c9b..8849c9b': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions`

**Comment by mattbrictson** [comment]
This sounds like a Capistrano issue. Does the problem still happen if you remove airbrussh from the project?

**Comment by jaipandya** [comment]
I looked at the full log that airbrussh puts in log/capistrano.log and
there was no error in that file. Which gives me a hint that it was
airbrussh specific. I haven't tried removing airbrussh from the project
though.

**Comment by mattbrictson** [comment]
To help troubleshoot can you:

1. Run the`cap` command that is failing, but with the `--trace` option added; copy and paste the resulting stack trace here
2. Try again with `require "airbrussh/capistrano"` commented out (in `Capfile`)

This will help narrow down where the error is happening, and whether or not it is airbrussh-related.

Thanks!

**Comment by jaipandya** [comment]
This is a bit strange, but now I'm not able to reproduce the issue. Tried a couple of times, but I see it all happening fine. If I see the issue next time again, I'll try the suggested options and update this thread.

**Comment by mattbrictson** [comment]
@jaipandya if you run into this again, let me know and I'll re-open.
