### ISSUE TITLE
Make rake a gem dependency

### ISSUE THREAD

**Issue by pblesi** [mattbrictson/airbrussh#126]
Airbrussh depends on Rake, but Rake is not a gem dependency, only a development dependency:

https://github.com/mattbrictson/airbrussh/blob/915bed8ec8d7cff7887e9b4725037d973e6b1931/airbrussh.gemspec#L27

https://github.com/mattbrictson/airbrussh/blob/915bed8ec8d7cff7887e9b4725037d973e6b1931/lib/airbrussh/rake/context.rb#L1

https://github.com/mattbrictson/airbrussh/blob/915bed8ec8d7cff7887e9b4725037d973e6b1931/lib/airbrussh/rake/context.rb#L58

Rake should be added as a dependency of airbrussh. Someone ran into this issue in a downstream project: https://github.com/braintree/runbook/issues/9

**Comment by mattbrictson** [comment]
Thanks for the report!

It seems that we only need rake if the airbrussh config `monkey_patch_rake` is set to `true`. By default it is `false`. It is only set to `true` when operating under capistrano, and capistrano already has rake as an explicit dependency.

So I think airbrussh should operate fine without rake as a runtime dependency, if we are more careful about doing `require "rake"` only when `monkey_patch_rake` is set to `true`.

I'll put up a PR.

**Comment by mattbrictson** [comment]
Fixed in airbrussh 1.3.3 https://github.com/mattbrictson/airbrussh/releases/tag/v1.3.3

**Comment by pblesi** [comment]
:fireworks: Thanks!
