### ISSUE TITLE
Switch from alias_method to prepend

### ISSUE THREAD

**Issue by benebrice** [mattbrictson/airbrussh#151]
There are conflict with libs (Hi [Sentry ✌🏻!](https://bytemeta.vip/repo/getsentry/sentry-ruby/issues/1873)). 

We might need to switch from `alias_method` to `prepend` here:

https://github.com/mattbrictson/airbrussh/blob/d440931db4f593fd0dbf14e310d6173f9b6973d3/lib/airbrussh/rake/context.rb#L58

**Comment by mattbrictson** [comment]
Thanks for the heads up!

This will be a bit tricky, because airbrussh needs to support Ruby as old as Ruby 1.9. `Module#prepend` was introduced in 2.0. If you have any suggestions, let me know!

**Comment by mattbrictson** [comment]
@benebrice can you test the branch in this PR to see if it solves the problem? #152

**Comment by benebrice** [comment]
It seams okay @mattbrictson ! Thanks a lot! 
I will be able to skip I made

```ruby
# config/initializers/airbrussh.rb
if defined?(Airbrussh)
  Airbrussh.configuration.monkey_patch_rake = false
end
```

**Comment by benebrice** [comment]
Thanks @mattbrictson !

Actually, I'm not able to test it properly. I cannot even run the `cap` command. 

```bash
root@f627dd4a0252:/tss_rails# cap staging deploy --trace
Traceback (most recent call last):
	8: from /usr/local/bundle/bin/cap:23:in `<main>'
	7: from /usr/local/lib/ruby/2.7.0/rubygems.rb:297:in `activate_bin_path'
	6: from /usr/local/lib/ruby/2.7.0/rubygems.rb:297:in `synchronize'
	5: from /usr/local/lib/ruby/2.7.0/rubygems.rb:298:in `block in activate_bin_path'
	4: from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:1371:in `activate'
	3: from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `activate_dependencies'
	2: from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:1389:in `each'
	1: from /usr/local/lib/ruby/2.7.0/rubygems/specification.rb:1400:in `block in activate_dependencies'
/usr/local/lib/ruby/2.7.0/rubygems/dependency.rb:311:in `to_specs': Could not find 'airbrussh' (>= 1.0.0) among 312 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/root/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle', execute `gem env` for more information
```

I've simply update the Gemfile with

```ruby
# Gemfile
gem 'airbrussh', git: 'https://github.com/mattbrictson/airbrussh.git', branch: 'features/use-prepend-if-supported'
```

```ruby
# Gemfile.lock
GIT
  remote: https://github.com/mattbrictson/airbrussh.git
  revision: 6a9b7ac68521d37d59285c10155e2e922807fc56
  branch: features/use-prepend-if-supported
  specs:
    airbrussh (1.4.2)
      sshkit (>= 1.6.1, != 1.7.0)

... 
GEM
  remote: https://rubygems.org/
  specs:
    capistrano (3.17.3)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)


...



DEPENDENCIES
  airbrussh!


```


It seems not to be properly installed. Maybe it's a version conflict somehow?

**Comment by mattbrictson** [comment]
@benebrice can you try `bundle exec cap`?

**Comment by benebrice** [comment]
It worked with `bundle exec cap` @mattbrictson 

Could you explain me why?

**Comment by mattbrictson** [comment]
@benebrice thanks for verifying!

> It worked with `bundle exec cap` Could you explain me why?

When you run the bare `cap` command, Ruby executes the version of Capistrano and its dependencies that are installed globally on your system for that version of Ruby. It completely ignores `Gemfile.lock`.

To install a gem from a git branch, the easy way to do it is via Bundler, by adding it to a `Gemfile` and then running `bundle install`, which updates `Gemfile.lock`. Installing a gem from a git branch does not install it globally. This is a Bundler-specific feature.

So when you run the bare `cap` command, Ruby is unaware of the `airbrussh` gem that Bundler obtained from git. The only way Ruby knows about it is if you run `cap` via Bundler. When you run `bundle exec cap`, Bundler steps in and looks at the `Gemfile.lock`, and uses that to find the gems. That is why you need `bundle exec` to be able to use git-sourced gems.

**Comment by benebrice** [comment]
Wonderful explanation. Thanks a lot for this and for the fix!
