### ISSUE TITLE
When to drop Ruby 1.9 support?

### ISSUE THREAD

**Issue by mattbrictson** [mattbrictson/airbrussh#16]
Airbrussh currently runs fine on Ruby 1.9 and up. However since Ruby's maintainers have officially [dropped all support for 1.9](https://www.ruby-lang.org/en/news/2015/02/23/support-for-ruby-1-9-3-has-ended/), it doesn't really make sense to devote our time to supporting a dead version of Ruby.

Can Airbrussh safely stop supporting 1.9? Are there a lot of Airbrussh users still on 1.9? (Seems there is [at least one](https://github.com/mattbrictson/airbrussh/issues/9).)

Suggestions, speculation, and discussion welcome! :smiley: 

Here are some ideas:

* Maintain 1.9 support as long as SSHKit and Capistrano do
* Drop 1.9 support now (no time like the present!)
* Wait until Airbrussh 1.0 (which will be…?)

/cc @robd @carlesso

**Comment by robd** [comment]
When I initially mentioned ruby versions, I hadn't realised that we supported it. In actual fact, I haven't found any cases where it was an issue (apart from adding a missing UTF-8 comment to a test). Unless it starts becoming an overhead, I reckon we should support it in versions where SSHKit supports it, especially if we are going to try and get Airbrussh merged into SSHKit.

**Comment by mattbrictson** [comment]
Good points. Let's track SSHKit and keep 1.9 support around as long as SSHKit does.
