### ISSUE TITLE
Make FormatterTest a true integration test by running actual rake tasks

### ISSUE THREAD

**Issue by mattbrictson** [mattbrictson/airbrussh#23]
Good idea from @robd, who [wrote](https://github.com/mattbrictson/airbrussh/pull/21#issuecomment-114863944):

> change the formatter tests to execute a real rake task and get rid of the `Airbrussh::Rake::Context.current_task_name = xxx` declarations in the tests. I had a crack at this in robd@ebdad32

This could follow a pattern similar to what is used `Rake::ContextTest` to define and invoke rake tasks during tests. The `define_and_invoke_rake_task` helper could be shared via a mixin, defined in `test/support`.

**Comment by robd** [comment]
I'm going to look at this now.

**Comment by mattbrictson** [comment]
Done in fc6aaa0.
