### ISSUE TITLE
Proposal - Remove support for temporary SSHKit formatter API

### ISSUE THREAD

**Issue by robd** [mattbrictson/airbrussh#26]
The [`CommandOutput`](https://github.com/mattbrictson/airbrussh/blob/ec3122b101de53f2304723da842d5c8b6f70f4f3/lib/airbrussh/command_output.rb) Facade was introduced to support SSHKit from https://github.com/capistrano/sshkit/commit/c92018da4ac71beb168a260c9fdfe58a8b7a685f up to  https://github.com/capistrano/sshkit/commit/a23836ce541cc5e8cf43350f0b4aa854cb8b1ab8. Since none of these commits was ever released, I propose we drop support for them in Airbrussh. 

This would allow us to remove the `Modern` `CommandOutput` and inline the logic from the `Legacy` one.

**Comment by mattbrictson** [comment]
:+1:

**Comment by robd** [comment]
I'm going to look at this now.

**Comment by mattbrictson** [comment]
Done in efe342c.
