### ISSUE TITLE
Usage fails when log directory doesn't exist

### ISSUE THREAD

**Issue by mateomurphy** [mattbrictson/airbrussh#30]
Non rails apps don't necessarily have a directory called `log`; it might be good to check for it's existence and create it to avoid error

**Comment by mattbrictson** [comment]
Would you prefer it make the directory if it doesn't already exist? I.e. an equivalent to `mkdir -p log`.

**Comment by mateomurphy** [comment]
Yes, I think that's fine

**Comment by mattbrictson** [comment]
This is implemented in 2abcc1b and will be included in the upcoming 0.6.0 (no ETA yet).

**Comment by mateomurphy** [comment]
Great! thanks

**Comment by mattbrictson** [comment]
I released airbrussh 0.6.0 today with this included.
