### ISSUE TITLE
Changelog entry for 0.6 is too awesome

### ISSUE THREAD

**Issue by jaredbeck** [mattbrictson/airbrussh#56]
This is the best changelog entry I've ever seen.  It tells me exactly what I need to know, in such a friendly way.

----

![screen shot 2015-07-14 at 4 54 51 pm](https://cloud.githubusercontent.com/assets/380809/8684927/2a9b5ad0-2a49-11e5-97df-60a71ee33009.png)

----

Please close this issue once you realize how awesome you are.

**Comment by mattbrictson** [comment]
Thanks @jaredbeck ! This is the best bug report I've ever received. :smile:
