### ISSUE TITLE
Option to disable banner output

### ISSUE THREAD

**Issue by mattbrictson** [mattbrictson/airbrussh#6]
As suggested by @justindowning:

> For my uses, could we add a flag that could be called per task to not output the `write_banner`? This would encourage more machine readable output for tasks the depend on it. Thanks! https://github.com/mattbrictson/airbrussh/blob/e3a8c5aeaaf8345ade13ddc981fb5b924f9cfb37/lib/airbrussh/formatter.rb#L55-L59

**Comment by mattbrictson** [comment]
Implemented in e4ab534.

**Comment by justindowning** [comment]
This is fantastic (and quickly implemnted)!! Thanks @mattbrictson :heart: !!
