### ISSUE TITLE
Log all error

### ISSUE THREAD

**Issue by lecoueyl** [mattbrictson/airbrussh#61]
If there is an error while deploying, airbrussh will not log the Backtrace output.
This will not be logged:

```
00:07 deploy:check:repo_dir
      01 mkdir -p /opt/test/
    ✔ 01 @test
(Backtrace restricted to imported tasks)
cap aborted!
NameError: undefined local variable or method `aaa' for #<SSHKit::Backend::Local:0x007fd45d3bbf30>
/opt/capistrano/tasks/bundle_rsync.cap:54:in `block (5 levels) in <top (required)>'
/opt/capistrano/tasks/bundle_rsync.cap:53:in `block (4 levels) in <top (required)>'
/opt/capistrano/tasks/bundle_rsync.cap:52:in `block (3 levels) in <top (required)>'
Tasks: TOP => bundle_rsync:rsync_release => bundle_rsync:npm:install
(See full trace by running task with --trace)
The deploy has failed with an error: undefined local variable or method `aaa' for #<SSHKit::Backend::Local:0x007fd45d3bbf30>

** DEPLOY FAILED
** Refer to test.log for details. Here are the last 20 lines:
```

It would be great if all the output would be logged, and not only the capistrano output

(Airbrussh is really sweet BTW!)

**Comment by mattbrictson** [comment]
Thanks for the report!

I see in your example that there is a backtrace being printed, but I assume it is being printed to stderr only. Is your idea that in addition to stderr, the backtrace should also be printed to the log file (`log/capistrano.log`)? I just want to make sure I understand the feature request.

**Comment by lecoueyl** [comment]
Yes that's right. It would be more useful in case of error to have all the stderr in the log file.
With the current output you now where it stopped but you don't know the reason

**Comment by mattbrictson** [comment]
OK, I got it. Thanks. I don't have time to consider this feature at the moment, but I would consider a PR.

**Comment by lecoueyl** [comment]
Okay, I will try to find a nice solution to implement it :+1:  (if I can)
