### ISSUE TITLE
undefined method `invoke_with_build_args' for nil:NilClass

### ISSUE THREAD

**Issue by wanzhou** [mattbrictson/airbrussh#68]
`gem install -l redis-3.2.2.gem `:
ERROR:  Loading command: install (LoadError)
        /home/test/tools/ruby/lib/ruby/2.0.0/x86_64-linux/openssl.so: undefined symbol: d2i_ECPKParameters - /home/test/tools/ruby/lib/ruby/2.0.0/x86_64-linux/openssl.so
ERROR:  While executing gem ... (NoMethodError)
    undefined method `invoke_with_build_args' for nil:NilClass

why? red hat 6

**Comment by mattbrictson** [comment]
It looks like you are having trouble installing the redis gem? I don't think this is airbrussh related, so I will close this issue. You may want to report the issue here instead: https://github.com/redis/redis-rb
