### ISSUE TITLE
Running from Pseudoterminals (PTY) outputs nothing when truncation is set to auto

### ISSUE THREAD

**Issue by PatKoperwas** [mattbrictson/airbrussh#75]
Running Airbrussh from Pseudoterminals (PTY) never outputs anything. Take this script for example:

```ruby
require "pty"

PTY.spawn("cap staging deploy") do |stdout, stdin, pid|
  begin
    stdout.each { |line| print line }
  rescue Errno::EIO
  end
end
```

[Console Width](https://github.com/mattbrictson/airbrussh/blob/449f621835600fc93916a52be93db139aa30b3fd/lib/airbrussh/console.rb#L58) gets calculated to 0 (make sense - there's no actual console / window this is running from). Can be easily fixed by setting `config.truncate = false`.

Not sure if this is something you want to add to the README or have it skip truncation if `console_width` ends up being 0.

**Comment by mattbrictson** [comment]
Fixed by #76
