### ISSUE TITLE
Allow prompt for '[sudo] password for' and 'Sorry, try again' to propagate to console

### ISSUE THREAD

**Issue by robd** [mattbrictson/airbrussh#8]
For some historic reasons, I can't easily use passwordless sudo, so I'm using this gem: https://github.com/kentaroi/sshkit-sudo, which handles capturing the password.

The problem is that the following log lines don't make it through to the console:

    DEBUG [7e0bb996] 	[sudo] password for whoever: 
    DEBUG [7e0bb996] 	
    DEBUG [7e0bb996] 	Sorry, try again.
    DEBUG [7e0bb996] 	
    DEBUG [7e0bb996] 	[sudo] password for whoever: 

Is there a way I can tell airbrussh to allow these lines to be shown?

**Comment by mattbrictson** [comment]
Yes, you will need the latest version of airbrussh (0.3.0). Try adding this to your `deploy.rb`:

```ruby
Airbrussh.configuration.command_output = :stdout
```

This will make the airbrussh output a little more verbose, but now you should be able to see the `[sudo]` prompts.

**Comment by robd** [comment]
Ah yes - perfect, thanks.
