### ISSUE TITLE
annoying log with capistrano/npm

### ISSUE THREAD

**Issue by eelp-juanma** [mattbrictson/airbrussh#83]
Hi,

When using [capistrano/npm](https://github.com/capistrano/npm) it shows a really addinfinitum log like this:

`00:13 npm:install
      01 npm install --production --silent --no-progress
      01 -
      01 \
      01 |
      01 /
      01 -
      01 \
      01 |
      01 /
      01 -
      01 \
      01 |
      01 /
      01 -
      01 \
      01 |
      01 /
      01 -
      01 \`
[...]
`01 \
      01 |
      01 /
      01 -
      01 expose-loader@0.7.1 node_modules/expose-loader
      01
      01 mirror-creator@1.1.0 node_modules/mirror-creator
      01
      01 babel@6.5.2 node_modules/babel
      01
      01 react-dom@15.1.0 node_modules/react-dom`

the log part with the packages installed is fine but the spinning cog are like 100 lines or more and is sad :(

Regards,
juanma

**Comment by mattbrictson** [comment]
Seems to me this is an npm issue. I see you are passing `--no-progress` to npm, yet it is showing a progress spinner anyway. I don't think there's is much Airbrussh itself can do to prevent this.

**Comment by mattbrictson** [comment]
I think you should add `--no-spin` to your npm command, which will solve the issue.
