### ISSUE TITLE
Some airbrussh output is "invisible" in certain terminal color schemes

### ISSUE THREAD

**Issue by mattbrictson** [mattbrictson/airbrussh#84]
We've received multiple reports (from @Startouf and @dan-klasson in https://github.com/capistrano/capistrano/issues/1669) that important error messages are not being rendered by Airbrussh.

Specifically, the color of the message is indistinguishable from the background color of the terminal, making them "invisible".

Suggestions of how to reproduce this (what OS and terminal is affected?) and how to fix it would be greatly appreciated.

![234c8794-1612-11e6-9f86-00bf3e6686e3](https://cloud.githubusercontent.com/assets/189693/16595083/08016568-42b3-11e6-910c-700b6d766b01.png)

**Comment by huerlisi** [comment]
Same issue here. I'm using the 'Solarized' Color Scheme of KDE's Konsole in version 15.08.0 as provided by Ubuntu 15.10.

**Comment by dan-klasson** [comment]
I'm using  'Solarized' Color Scheme on Ubuntu Gnome 16.04

**Comment by mattbrictson** [comment]
Thanks for the additional data points.

Can both of you run this simple script in irb and post a screenshot of your output?

```ruby
gem "airbrussh", "1.0.2"
require "airbrussh/colors"
Airbrussh::Colors::ANSI_CODES.keys.each do |color|
  puts Airbrussh::Colors.public_send(color, color)
end
```

Here's what I see:

![screen shot 2016-07-26 at 9 47 23 am](https://cloud.githubusercontent.com/assets/189693/17147116/2904b4a4-5316-11e6-85be-dc2b9e2d85c4.png)

**Comment by huerlisi** [comment]
Only `solarized` has the issue. Even `solarized light` uses a proper gray:
![solarized](https://cloud.githubusercontent.com/assets/11375/17152607/cfe01518-5378-11e6-9b99-19e1095e0cea.png)

![solarized-light](https://cloud.githubusercontent.com/assets/11375/17152609/d50f7ace-5378-11e6-91e8-7b88d5236ea4.png)

So it's probably an issue with the solarized theme.

**Comment by mattbrictson** [comment]
Great, looks like we've got this figured out.

I know that solarized is popular, and I don't want Airbrussh to obscure important messages when people are using it with solarized. I think that warrants changing Airbrussh's default colors (even if solarized is ultimately at fault).

Do you agree?

Right now Airbrussh uses the gray to display `info` log messages (e.g. "linked file does not exist", upload progress, etc.), and also the time elapsed for each command. If we don't use gray for those because of the solarized issue, what color should we use instead?

**Comment by huerlisi** [comment]
Cool!

I'd go with the default color, like the irb output.

**Comment by mattbrictson** [comment]
Any chance you'd be willing to do a PR? It should just be a matter of removing the use of `gray` from `command_formatter.rb` and `console_formatter.rb` and then updating the expected output in the tests.

**Comment by huerlisi** [comment]
Yepp, can give it a try:-)

**Comment by huerlisi** [comment]
PR created, please review:-)

**Comment by huerlisi** [comment]
@mattbrictson upstream issue filed in KDE: https://bugs.kde.org/show_bug.cgi?id=366143

@dan-klasson maybe you want to also file an issue in Gnome and link this and the KDE bug.
